<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ShantyMongo\Module'                    => __DIR__ . '/Module.php',
  'Shanty\Mongo'                          => __DIR__ . '/library/Shanty/Mongo.php',
  'Shanty\Paginator\Adapter\Mongo'        => __DIR__ . '/library/Shanty/Paginator/Adapter/Mongo.php',
  'Shanty\Mongo\DocumentSet'              => __DIR__ . '/library/Shanty/Mongo/DocumentSet.php',
  'Shanty\Mongo\Iterator\DefaultIterator' => __DIR__ . '/library/Shanty/Mongo/Iterator/DefaultIterator.php',
  'Shanty\Mongo\Iterator\Cursor'          => __DIR__ . '/library/Shanty/Mongo/Iterator/Cursor.php',
  'Shanty\Mongo\Exception'                => __DIR__ . '/library/Shanty/Mongo/Exception.php',
  'Shanty\Mongo\Collection'               => __DIR__ . '/library/Shanty/Mongo/Collection.php',
  'Shanty\Mongo\Document'                 => __DIR__ . '/library/Shanty/Mongo/Document.php',
  'Shanty\Mongo\Validator\StubTrue'       => __DIR__ . '/library/Shanty/Mongo/Validator/StubTrue.php',
  'Shanty\Mongo\Validator\ArrayValidator' => __DIR__ . '/library/Shanty/Mongo/Validator/ArrayValidator.php',
  'Shanty\Mongo\Validator\ClassValidator' => __DIR__ . '/library/Shanty/Mongo/Validator/ClassValidator.php',
  'Shanty\Mongo\Connection'               => __DIR__ . '/library/Shanty/Mongo/Connection.php',
  'Shanty\Mongo\Connection\Stack'         => __DIR__ . '/library/Shanty/Mongo/Connection/Stack.php',
  'Shanty\Mongo\Connection\Group'         => __DIR__ . '/library/Shanty/Mongo/Connection/Group.php',
);
